use std::collections::HashMap;

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Language {
    French,
    English,
}

pub fn get_text(key: &str, language: Language) -> String {
    match language {
        Language::French => get_french_text(key),
        Language::English => get_english_text(key),
    }
}

fn get_french_text(key: &str) -> String {
    let translations: HashMap<&str, &str> = [
        ("language", "Langue"),
        ("new_file", "Nouveau Fichier"),
        ("open_project", "Ouvrir Projet"), 
        ("canvas_settings", "Paramètres du canevas"),
        ("modern_paint_application", "Application de peinture moderne"),
        ("canvas_dimensions", "Dimensions du canevas"),
        ("width", "Largeur:"),
        ("height", "Hauteur:"),
        ("create_new_canvas", "Créer un nouveau canevas"),
        ("open_png", "Ouvrir un fichier PNG"),
        ("open_rustiq", "Ouvrir un fichier Rustiq"),
        ("open_file", "Ouvrir un fichier"),
        ("layers", "Calques"),
        ("tools", "Outils"),
        ("save_options", "Options de sauvegarde"),
        ("layer", "Calque"),
        ("up", "Haut"),
        ("down", "Bas"),
        ("brush", "Pinceau"),
        ("eraser", "Gomme"),
        ("paint_bucket", "Pot de peinture"),
        ("color_picker", "Pipette"),
        ("line", "Ligne"),
        ("brush_size", "Taille du pinceau:"),
        ("eraser_size", "Taille de la gomme:"),
        ("colors", "Couleurs:"),
        ("primary", "Primaire:"),
        ("secondary", "Secondaire:"),
        ("zoom", "Zoom:"),
        ("saved_colors", "Couleurs sauvegardées:"),
        ("left_click_primary", "Clic gauche: définir comme couleur primaire"),
        ("right_click_secondary", "Clic droit: définir comme couleur secondaire"),
        ("middle_click_delete", "Clic molette: supprimer"),
        ("return_to_menu", "Retour au menu"),
        ("undo", "Annuler"),
        ("redo", "Refaire"),
        ("save_png", "Sauvegarder PNG"),
        ("save_rustiq", "Sauvegarder Rustiq"),
        ("save_file", "Sauvegarder Fichier"),
        ("shortcuts_info", "Clic droit: couleur secondaire | Ctrl+Z: Annuler | Ctrl+Y: Refaire | Ctrl+S: Sauvegarder"),
        ("error", "Erreur"),
        ("an_error_occurred", "Une erreur s'est produite"),
        ("save_changes", "Sauvegarder les modifications?"),
        ("want_to_save_changes", "Voulez-vous sauvegarder les modifications?"),
        ("yes", "Oui"),
        ("no", "Non"),
        ("cancel", "Annuler"),
        ("rename_layer", "Renommer le calque"),
        ("format_not_supported", "Format de fichier non pris en charge"),
        ("no_previous_path", "Aucun chemin de sauvegarde précédent"),
        ("unable_to_open_png", "Impossible d'ouvrir l'image PNG"),
        ("unable_to_open_image", "Impossible d'ouvrir l'image"),
        ("error_reading_rustiq", "Erreur lors de la lecture du fichier Rustiq"),
        ("error_reading_file", "Erreur lors de la lecture du fichier"),
        ("error_saving_png", "Erreur lors de la sauvegarde PNG"),
        ("error_saving_image", "Erreur lors de la sauvegarde de l'image"),
        
        ("properties", "Propriétés"),
        ("brush_system", "Système de pinceaux"),
        ("tool_settings", "Paramètres d'outils"),
        ("pressure_settings", "Paramètres de pression"),
        ("enable_pressure", "Activer la pression"),
        ("smoothing", "Lissage"),
        ("velocity_sensitivity", "Sensibilité de vélocité"),
        ("max_velocity", "Vélocité maximale"),
        ("current", "Actuel"),
        ("affects_size", "Affecte la taille"),
        ("min_size", "Taille minimale"),
        ("affects_opacity", "Affecte l'opacité"),
        ("min_opacity", "Opacité minimale"),
        ("zoom", "Zoom :"),
        ("brush_selection", "Sélection du pinceau"),
        ("select_brush", "Sélectionner un pinceau"),
        ("brush_round", "Rond"),
        ("brush_flat", "Plat"),
        ("brush_bright", "Brillant"),
        ("brush_filbert", "Filbert"),
        ("brush_fan", "Éventail"),
        ("brush_angle", "Angle"),
        ("brush_mop", "Mop"),
        ("brush_rigger", "Rigger"),
        ("brush_custom", "Personnalisé"),
        ("load_texture", "Charger Texture"),
        ("select_brush_texture", "Sélectionner une texture de pinceau"),
        ("custom_brushes", "Pinceaux personnalisés"),
        ("delete", "Supprimer"),
    ].iter().cloned().collect();
    
    translations.get(key).unwrap_or(&key).to_string()
}

fn get_english_text(key: &str) -> String {
    let translations: HashMap<&str, &str> = [
        ("language", "Language"),
        ("new_file", "New File"),
        ("open_project", "Open Project"),
        ("canvas_settings", "Canvas Settings"),
        ("modern_paint_application", "Modern Paint Application"),
        ("canvas_dimensions", "Canvas Dimensions"),
        ("width", "Width:"),
        ("height", "Height:"),
        ("create_new_canvas", "Create New Canvas"),
        ("open_png", "Open PNG File"),
        ("open_rustiq", "Open Rustiq File"),
        ("open_file", "Open File"),
        ("layers", "Layers"),
        ("tools", "Tools"),
        ("save_options", "Save Options"),
        ("layer", "Layer"),
        ("up", "Up"),
        ("down", "Down"),
        ("brush", "Brush"),
        ("eraser", "Eraser"),
        ("paint_bucket", "Paint Bucket"),
        ("color_picker", "Color Picker"),
        ("line", "Line"),
        ("brush_size", "Brush Size:"),
        ("eraser_size", "Eraser Size:"),
        ("colors", "Colors:"),
        ("primary", "Primary:"),
        ("secondary", "Secondary:"),
        ("zoom", "Zoom:"),
        ("saved_colors", "Saved Colors:"),
        ("left_click_primary", "Left-click: set as primary color"),
        ("right_click_secondary", "Right-click: set as secondary color"),
        ("middle_click_delete", "Middle-click: delete"),
        ("return_to_menu", "Return to Menu"),
        ("undo", "Undo"),
        ("redo", "Redo"),
        ("save_png", "Save PNG"),
        ("save_rustiq", "Save Rustiq"),
        ("save_file", "Save File"),
        ("shortcuts_info", "Right-click: secondary color | Ctrl+Z: Undo | Ctrl+Y: Redo | Ctrl+S: Save"),
        ("error", "Error"),
        ("an_error_occurred", "An error occurred"),
        ("save_changes", "Save Changes?"),
        ("want_to_save_changes", "Do you want to save changes?"),
        ("yes", "Yes"),
        ("no", "No"),
        ("cancel", "Cancel"),
        ("rename_layer", "Rename Layer"),
        ("format_not_supported", "File format not supported"),
        ("no_previous_path", "No previous save path"),
        ("unable_to_open_png", "Unable to open PNG image"),
        ("unable_to_open_image", "Unable to open image"),
        ("error_reading_rustiq", "Error reading Rustiq file"),
        ("error_reading_file", "Error reading file"),
        ("error_saving_png", "Error saving PNG"),
        ("error_saving_image", "Error saving image"),
        ("properties", "Properties"),
        ("brush_system", "Brush System"),
        ("tool_settings", "Tool Settings"),
        ("pressure_settings", "Pressure Settings"),
        ("enable_pressure", "Enable Pressure"),
        ("smoothing", "Smoothing"),
        ("velocity_sensitivity", "Velocity Sensitivity"),
        ("max_velocity", "Max Velocity"),
        ("current", "Current"),
        ("affects_size", "Affects Size"),
        ("min_size", "Min Size"),
        ("affects_opacity", "Affects Opacity"),
        ("min_opacity", "Min Opacity"),
        ("zoom", "Zoom:"),
        ("brush_selection", "Brush Selection"),
        ("select_brush", "Select Brush"),
        ("brush_round", "Round"),
        ("brush_flat", "Flat"),
        ("brush_bright", "Bright"),
        ("brush_filbert", "Filbert"),
        ("brush_fan", "Fan"),
        ("brush_angle", "Angle"),
        ("brush_mop", "Mop"),
        ("brush_rigger", "Rigger"),
        ("brush_custom", "Custom"),
        ("load_texture", "Load Texture"),
        ("select_brush_texture", "Select brush texture"),
        ("custom_brushes", "Custom Brushes"),
        ("delete", "Delete"),
    ].iter().cloned().collect();
    
    translations.get(key).unwrap_or(&key).to_string()
}